#!/usr/bin/env bash
cli_log() {
  local timestamp script_name
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  echo "== $script_name $timestamp $1"
}

create_config() {
  echo "$1=$2" >./config
}

append_config() {
  echo "$1=$2" >>./config
}
