#!/usr/bin/env bash
set -e

CLI_WORKDIR="${BASH_SOURCE%/*}"
if [[ ! -d "$CLI_WORKDIR" ]]; then CLI_WORKDIR="$PWD"; fi
export CLI_WORKDIR

CLI_COMMANDS=("$CLI_WORKDIR/commands")
export CLI_COMMANDS

CLI_LOGS=("$CLI_WORKDIR/logs")
export CLI_LOGS

CLI_CONFIG=$CLI_WORKDIR/config
export CLI_CONFIG

# shellcheck source=common
source "$CLI_WORKDIR/common"

cli_help() {
  local cli_name=${0##*/}
  echo "
Developer CLI
Version: $(cat "$CLI_WORKDIR"/VERSION)
https://github.com/klement97/dev-cli

Usage: $cli_name [command]

Commands:
  deploy    Deploy
  *         Help
"
  exit 1
}

case "$1" in

configure | c)
  "$CLI_COMMANDS/configure" | tee -ia "$CLI_LOGS/configure.log"
  ;;

startb | b)
  # shellcheck source=commands/start_backend
  . "$CLI_COMMANDS/start_backend"
  startb | tee -ia "$CLI_LOGS/start_backend.log"
  ;;

*)
  cli_help
  ;;
esac
